sudo: required
services:
  - docker

before_install: 
  - docker build -t mena5800/react-test -f ./client/dockerfile.dev ./client

script: 
  - docker run -e CI=true mena5800/react-test npm run test -- --watchAll=false

after_success: 
  - docker build -t mena5800/multi-client ./client
  - docker build -t mena5800/multi-nginx ./nginx
  - docker build -t mena5800/multi-server ./server
  - docker build -t mena5800/multi-worker ./worker
