version: "3"
services:
  client:
    image: "mena5800/multi-client"
    hostname: client
    mem_limit: 128m

  redis:
    image: "redis:latest"
    mem_limit: 128m
  
  server:
    image: "mena5800/multi-server"
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    mem_limit: 128m

  worker:
    image: "mena5800/multi-worker"
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    mem_limit: 128m

  nginx:
    image: "mena5800/multi-nginx"
    hostname: nginx
    mem_limit: 128m
    ports:
      - "80:80"
